# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: default

steps:
- script: python3 hello_world.py
  displayName: 'Run a python script that prints hello world'

- script: python3 test_hello_world.py
  displayName: 'Run python unit test of hello world print statement'
